### ISSUE TITLE
Hexadecimal indicator is not allowed

### ISSUE THREAD

**Issue by birjj** [HandsomeOne/JavaScript24#2]
`0x` is not allowed unless one of your digits is `0`.

[main.js#L59](https://github.com/HandsomeOne/JavaScript24/blob/df93d0386025dc282cc2fee58801380d28fa64b8/js/main.js#L59):

```
.replace(/0x/ig, '0')
```

Should be

```
.replace(/0x/ig, '').
```

As it is now, `0x1234` becomes `01234`. If you have the digits `1234`, they are removed in the for-loop, giving you `0`. This fails the `e.test(/\d/)` test for rule 2.

**Comment by HandsomeOne** [comment]
Sorry for my poor English, but I meant it. So I have to modify the rule#2's description to `x`(after a given `0`) instead.

**Comment by birjj** [comment]
Nope, the description is good. You just need to change [line 59 in main.js](https://github.com/HandsomeOne/JavaScript24/blob/df93d0386025dc282cc2fee58801380d28fa64b8/js/main.js#L59), so that the last `.replace(/0x/ig, '0')` becomes `.replace(/0x/ig, '')`.
